# Generated by Django 5.2.4 on 2025-08-03 18:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_address_user_alter_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
