# Generated by Django 5.2.4 on 2025-08-03 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="url",
            new_name="image",
        ),
    ]
