# Generated by Django 5.2.4 on 2025-08-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_url_image_image"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vendor",
            table="vendor",
        ),
    ]
